# Generated by Django 5.2.7 on 2025-11-05 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0004_missingperson_category_alter_missingperson_status'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteersearch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='volunteersearch',
            name='person',
        ),
        migrations.RemoveField(
            model_name='volunteersearch',
            name='volunteer',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='active',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='viber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='VolunteerParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_participants', to='missing_persons.missingperson')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('volunteer', 'person')},
            },
        ),
        migrations.DeleteModel(
            name='VolunteerReport',
        ),
        migrations.DeleteModel(
            name='VolunteerSearch',
        ),
    ]
