# Generated by Django 5.2.7 on 2025-10-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='missing_persons/'),
        ),
    ]
