# Generated by Django 5.2.7 on 2025-10-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0002_alter_missingperson_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Останнє місце, де бачили'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
