# Generated by Django 5.2.7 on 2025-10-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0003_missingperson_latitude_missingperson_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='category',
            field=models.CharField(choices=[('child', 'Дитина'), ('adult', 'Дорослий'), ('elderly', 'Літня людина'), ('military', 'Військовий'), ('disabled', 'Людина з інвалідністю'), ('other', 'Інше')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('missing', 'У розшуку'), ('found', 'Знайдено')], default='missing', max_length=20),
        ),
    ]
